### ISSUE TITLE
Update tendermint-rs to v0.30?

### ISSUE THREAD

**Issue by lshoo** [penumbra-zone/tower-abci#24]
Tendermint-rs and -abci have already released v0.30 last week, and have some [breaking changes](https://github.com/informalsystems/tendermint-rs/blob/main/CHANGELOG.md#breaking-changes), and tendermint-rs v0.30 is re-export and support tendermint(cometbft) v0.37.
 
Will the tower-abci update the tendermint-rs dependecy soon? which tendermint version(0.34. or 0.37) is support default?

Thanks

**Comment by hdevalence** [comment]
Hey! We're planning to do this in our next (2-week) sprint cycle.

**Comment by hdevalence** [comment]
In progress: https://github.com/penumbra-zone/tower-abci/pull/25

**Comment by hdevalence** [comment]
> which tendermint version(0.34. or 0.37) is support default?

Our plan is to support both 0.34 and 0.37 side by side, so that tower-abci apps can more easily transition from 0.34 to 0.37.

**Comment by erwanor** [comment]
This is done in #25
