### ISSUE TITLE
tower-abci: add support for CometBFT `v0.38`

### ISSUE THREAD

**Issue by erwanor** [penumbra-zone/tower-abci#34]
Once #33 is completed, we should add support for `v0.38`. The reason to do this separately is that #33 reorganizes the modules into distinct strictly versioned units, which in itself is an important change. The plan right now is to:
- [x] implement #33 
- [x] release `v0.9.0`
- [x] add support for cometbft `v0.38` 
- [x] release `v0.11.0`

**Comment by hdevalence** [comment]
Doing this would give us optionality to release with 0.38 if desired.
