### ISSUE TITLE
Out-of-order transaction execution

### ISSUE THREAD

**Issue by aakoshh** [penumbra-zone/tower-abci#44]
This is not a problem with `tower-abci` per se, but I thought it would be a good place to at least ask the question and raise awareness. 

We had an issue where it appeared that in our service `deliver_tx` and `end_block` was called concurrently, that is, `end_block` was called before the last `deliver_tx` was finished, and later a consensus failure because different nodes applied transactions in different order, which was another sign that multiple `deliver_tx` calls were happening simultaneously. 

The reason I think is that our implementation of the `Service`, like the `kvstore` [example](https://github.com/penumbra-zone/tower-abci/blob/dc2d5efee8cd748b4d816563002c3f569d12b55a/examples/kvstore_37/main.rs#L40-L41), always returned `Ready` from `poll_ready`, and this is the only thing the `Worker` [awaits](https://github.com/penumbra-zone/tower-abci/blob/dc2d5efee8cd748b4d816563002c3f569d12b55a/src/buffer4/worker.rs#L131) on. If it's always ready, it [calls](https://github.com/penumbra-zone/tower-abci/blob/dc2d5efee8cd748b4d816563002c3f569d12b55a/src/buffer4/worker.rs#L134) the service, which creates another `Future` (but doesn't wait on it), and those can thus execute concurrently and out of order. 

I'm hoping to solve this by surrounding the `consensus` service after the split like [here](https://github.com/penumbra-zone/tower-abci/blob/dc2d5efee8cd748b4d816563002c3f569d12b55a/examples/kvstore_37/main.rs#L169-L175) with a `ServiceBuilder::new().buffer(1000).concurrency_limit(1).service(consensus)`, which hopefully will not report itself as ready until the previous call is finished. 

I can see that penumbra [doesn't use this split](https://github.com/penumbra-zone/penumbra/blob/f0dba4cf437a1a4836da827f6034b00c36a15f8b/crates/core/app/src/server.rs#L47-L53) mechanism, so it can make more intelligent decisions about when it's ready to receive more requests, but I'm wondering if the examples could draw attention to this potential issue. It's possible that the documentation mentions it and I just missed its significance.

**Comment by hdevalence** [comment]
Ouch, that is an unfortunate footgun indeed. If you want to send a docs PR that would be helpful!
